### ISSUE TITLE
Digest results from A2.3 (Light curves)

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#107]
Activity A2.3 (Light curve classification and features) has its own project board. The work from this will need to be absorbed into the general user requirements review

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @andyxerxes has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2352578725/A3.09+Report) for the A3.09 activity. At the above meeting it was agreed to close all tickets in the A3.09 current activity.
