### ISSUE TITLE
Analyse and review interaction with variability science

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#108]
General variability science will be done with the data releases from the DAC, but (a) there is a grey area between extreme variability and transients proper; (b) there is a need to react to outbursts, rather than just transients, and (c) even for transients, scientists will want the historical light curve.

The aim in this task is partly to think about the implications of this kind of science directly for Lasair requirements, but also to understand what the links need to be between Lasair and the rest of the DAC

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @andyxerxes has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2352578725/A3.09+Report) for the A3.09 activity. At the above meeting it was agreed to close all tickets in the A3.09 current activity.
