### ISSUE TITLE
Construct User Requirements Summary Document (URSD)

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#109]
Summarise results from the community review, the citizen science task, the LIGO task, the light curve classification project, and the analysis of general variability science, and put this into a the User Requirements Summary Document (URSD). Make sure this has a sense of what is realistically achievable, and set priorities.

**Comment by andyxerxes** [comment]
The User requirements review has now been completed and was very successful. Roy has written some notes - maybe Stephen should too? - but maybe also we could get some final thoughts from the organisers. This was one of several strands to put into the URSD, along with LIGO, citizen science, variability science, and light curve classification. I was thinking maybe we should start a wiki page where collect these strands together - although the URSD itself should be a proper document, not just a wiki page.

**Comment by andyxerxes** [comment]
I have made an overall[ Cycle 2 UI planning page](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/1276903430/Cycle+2+User+Interface+Planning) on the wiki, and under that a [URSD wiki page](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/1276772353/User+Requirements+Summary+Document+Development), for collecting info and thoughts to work towards writing the eventual Phase B Technical Document.

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @andyxerxes has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2352578725/A3.09+Report) for the A3.09 activity. At the above meeting it was agreed to close all tickets in the A3.09 current activity.
