### ISSUE TITLE
Construct Functionality Requirements Document (FRD)

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#110]
Analyse URSD to propose functionality requirements document (FRD). Analyse how this matches onto Tech.Architecture below and interface above, and interaction with expected DAC. (Questions like:  should we parse SQL, should we provide form-based querying, should we provide large watchlists)

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @andyxerxes has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2352578725/A3.09+Report) for the A3.09 activity. At the above meeting it was agreed to close all tickets in the A3.09 current activity.
