### ISSUE TITLE
Undertake Market Survey of related systems

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#111]
In order to progress to an actual design, as well as analysing requirements, and functionality issues, this would be a good time to look around at what else is ready or being developed on the world scene. This means other brokers - e.g. Antares, Alerce, Fink - but also technologies that we want to incorporate, such as Firefly, Jupyter Lab, Astroquery, PyVO etc.

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @andyxerxes has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2352578725/A3.09+Report) for the A3.09 activity. At the above meeting it was agreed to close all tickets in the A3.09 current activity.
