### ISSUE TITLE
Produce Design for User Interface

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#112]
This is the final goal of this project, within Cycle 2 - to actually end up with a *draft* design for the User Interface. Then in Cycle 3 we will see how this maps onto the Technical Architecture that we have developed.

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @andyxerxes has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2352578725/A3.09+Report) for the A3.09 activity. At the above meeting it was agreed to close all tickets in the A3.09 current activity.
