### ISSUE TITLE
Digest Results from A2.7 (queries)

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#113]
Activity 2.7 (Build set of representative queries) has its own kanban/project board. As this completes, we need to absorb the results into the general user requirements analysis.

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @andyxerxes has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2352578725/A3.09+Report) for the A3.09 activity. At the above meeting it was agreed to close all tickets in the A3.09 current activity.
