### ISSUE TITLE
Install REST API on lasair-dev and lasair-IRIS and configure test service

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#117]
https://www.django-rest-framework.org/

**Comment by genghisken** [comment]
Django REST framework installed on lasair-dev and lasair-IRIS.

**Comment by genghisken** [comment]
Currently learning how to configure a test service.

**Comment by genghisken** [comment]
Test cone search service configured and just about ready to deploy.  The service includes:

- Token authentication (which can be configured via the Django Admin interface)
- Cone search for a single ra / dec / radius input.

However, the IRIS systems appear to be down, so I can't deploy it to complete the configuration and testing.
