### ISSUE TITLE
Make 3-5 minute "flash" presentation for Rubin PCW session

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#130]
This needs to be submitted a week in advance, so attendees can view in advance and then use the session to ask questions.

We are thinking this should focus on the fact that our prototype is being used for real science, with the final design for LSST as secondary theme

**Comment by RoyWilliams** [comment]
How can we demonstrate the "real science" idea? Do we have papers, astronomerstelegram, or other citations? How about write to our colleagues and ask if they have used Lasair for real science?

**Comment by smarttgit** [comment]
Done by Stephen 

https://www.dropbox.com/sh/37tgjyv44p59n19/AACPdJEn6WRnmFV2QJUl5htba?dl=0
