### ISSUE TITLE
Make slide-deck for Rubin PCW session

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#131]
As well as our presentation, it seems like we should make a "slide deck". This can have the key features of the website, tutorial examples etc. Probably a good thing to do anyway!

**Comment by RoyWilliams** [comment]
8 slides in dropbox
Slide 2 is candy for the tired reader
https://www.dropbox.com/s/vsv9s9z3ym655c0/LasairPCW2020.pptx?dl=0
