### ISSUE TITLE
Integrate Cassandra into Lasair-LSST interface

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair#133]
Need to modify the code to allow the Lasair-LSST interface to collect the detections (diaSources) from Cassandra

**Comment by genghisken** [comment]
Web interface updated to allow polling of local single-node cassandra instance. Still to do is get the ingest working.

**Comment by RoyWilliams** [comment]
Waiting for #93 and #118

**Comment by genghisken** [comment]
Blockage caused by internal network problems has now been resolved.  Code modifications ongoing.

**Comment by genghisken** [comment]
Ongoing.  Code is in place, we just need to remove some flags to allow the Web interface to pull its detections from Cassandra, and not the avro files.

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @genghisken has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2326757394/Cassandra+Report+for+Lasair+Cycle+3) for the A3.04 activity. At the above meeting it was agreed all tickets in A3.04 should be marked as done then closed.
