### ISSUE TITLE
Modify ingester to put detections into Cassandra

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair#134]
Need to alter the ingester process to pick up the detections (and non-detections) from the ingestion stream and feed them into Cassandra.

**Comment by genghisken** [comment]
I have the code ready to insert the data into Cassandra. However, the ingester node (filter-dev) can't talk to the Cassandra cluster, which is on the SAME NETWORK.  No-one seems to know why this is the case.  No firewalls are active and no other relevant network config (e.g. ipconfig) seems to be active.  Cassandra nodes can talk to each other.  Cassandra nodes can talk to ingester node. But ingester node can't talk to Cassandra.

I've tried destroying and recreating the ingester node (filter-dev). No joy.  Tried a different "flavor" for the node.  No joy.  Can't move on this until this is fixed.  Something appears to have changed the "default" settings when creating a new OpenStack instance, but no-one seems to be able to tell me what it is...

Interestingly the new ingester node CAN talk to the internet, but not anything on its own network!!

**Comment by RoyWilliams** [comment]
Previous messages

But the problem still remains.  The cassandra nodes are not accessible from the filter-dev node - nothing to do with ssh keys!

I can trash & rebuild the filter-dev node with the right network settings if necessary.

-----------------------

I trashed the filter-dev node (192.168.0.10) and recreated it (now .24) & I'm re-running the filter.yml playbook (with a few extras I added) from lt-head.  Fine so far...

BUT - .24 STILL can't talk to the cassandra nodes.  Something very odd going on.  All cassandra nodes can talk to all other nodes (including filter-dev) but filter-dev can't talk to anything on the lasair-local network.

192.168.0.24 (filter-dev) and (e.g.) 192.168.0.20 (cassandra-node-1) are on the same network (lasair-local).  I can ssh from 20 to 24, but NOT the other way round.  What am I doing wrong?  Has something changed in the default OpenStack network configuration? I tried a rebuilding with a different "flavor" of the server and still it can't talk to any machine on the network (but other existing servers on the network can see it).

I can't proceed with Cassandra connectivity until this is resolved.

-----------------------

Have you checked your OpenStack security groups on the new node? Look at those, and see if they match those on the other nodes. That's the first thing to look at...

-----------------------
I've not run into this problem before.  Prior to last week any node I created could always talk to any other node on the lasair-local network.

All my nodes have identical security groups:

        ALLOW IPv4 22/tcp from 195.194.120.0/22
        ALLOW IPv6 to ::/0
        ALLOW IPv4 22/tcp from 129.215.0.0/16
        ALLOW IPv4 from default
        ALLOW IPv4 22/tcp from 10.65.128.0/17
        ALLOW IPv4 22/tcp from 192.108.120.0/24
        ALLOW IPv4 to 0.0.0.0/0
        ALLOW IPv4 22/tcp from 192.41.108.0/25
        ALLOW IPv4 3303/tcp from 0.0.0.0/0
        ALLOW IPv6 from default
        ALLOW IPv4 3306/tcp from 0.0.0.0/0

No difference at all between 192.168.0.24 and 192.168.0.20.  The latter can ping the former, but not vice versa!

-----------------------
Have you checked if the default ‘ufw’ service is running on 192.168.0.20? One directional problems are often firewall related.

-----------------------
The ufw service is inactive.

ubuntu@lt-head:~$ ssh -i ~/.ssh/id_rsa_ken_lasair ubuntu@192.168.0.24
ubuntu@filter-dev:~$ sudo ufw status
Status: inactive
ubuntu@filter-dev:~$ exit


ubuntu@lt-head:~$ ssh -i ~/.ssh/id_rsa_ken_lasair ubuntu@192.168.0.20
ubuntu@cassandra-node-1:~$ sudo ufw status
Status: inactive

**Comment by genghisken** [comment]
Network problems were fixed, and Roy & I have fixed the ingester so that data is now flowing into Cassandra.

**Comment by genghisken** [comment]
Ongoing.  Still to do - insert the "non-detections".  The code has been difficult to test recently because of lack of data from the telescope.  This will hopefully resolve itself very soon.

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @genghisken has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2326757394/Cassandra+Report+for+Lasair+Cycle+3) for the A3.04 activity. At the above meeting it was agreed all tickets in A3.04 should be marked as done then closed.
