### ISSUE TITLE
Evaluate Cassandra replication

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair#140]
We need to answer the following questions:

* What level of replication do we need?
* How fast does the inserted data propagate?
* Is replication reliable?
* How does adding a new node scale?  (Will the data need to be periodically rebalanced?)
* What happens when we destroy a node?
* How does it perform and recover?
* Will the data need to be periodically rebalanced as new nodes are introduced?
* How consistent are the responses I get back from Cassandra, given that I might not always be talking to the same node and the data may not yet have propagated to all the nodes?  (Do I need to introduce artificial delays to wait for consistency?)

**Comment by genghisken** [comment]
I've setup a cluster with a "keyspace" (== database) that has a replication factor of 3.

Replication happens fairly instantaneously when the data is being written.  It appears to be reliable.

The replication is happening, and removal of a single node has been shown to continue to allow access to all the data.  Testing of this is still ongoing.  Attempts on one node to truncate the table when another node is down results in a data consistency error warning.  When the node comes back, the consistency error goes away.  I still need to find out what happens when the node is destroyed completely.

I haven't tried adding a new node yet.

**Comment by genghisken** [comment]
This was blocked until #93 was done.  Now this is much easier to evaluate.

**Comment by genghisken** [comment]
The failure of the whole of OpenStack on 7th Feb shows that we need to figure out a way of backing up the binary data on each node. We also currently don't know how to add new nodes or recover broken individual nodes.

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @genghisken has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2326757394/Cassandra+Report+for+Lasair+Cycle+3) for the A3.04 activity. At the above meeting it was agreed all tickets in A3.04 should be marked as done then closed.
