### ISSUE TITLE
Evaluate Cassandra Hardware & Storage Requirements

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair#142]
* What are the CPU/Memory requirements of Cassandra?
* How much storage does each Cassandra node require?
* Do we need to allocate SSD?  If so, how is it attached to each Cassandra node?
* Can we compare read/write throughput for spinning disk and compare with SSD?
* Can I pull the data back in reasonable time?  How fast are reads and writes?

**Comment by genghisken** [comment]
Having deployed extremely minimal Cassandra nodes (2GB, 2CPUs, 20GB space), I now have a better understanding of how much resources should be allocated to each node (for memory and CPUs, at least 4GB and 4 CPUs).  In production, DataStax recommends 32GB memory and 16CPUs EACH!

I/O resource MUST be allocated to each node independently.  In other words, having the nodes talk to a common SAN, NAS or SSD is actually a design "antipattern".

On the extreme minimal nodes I can get 20,000 writes per minute, but they run out of memory very quickly as Cassandra deploys the various "gossiping" processes to keep the data flowing between the nodes.

I have yet to test read speed.

**Comment by genghisken** [comment]
Since #93 is now done, this is now much easier to do.  I can destroy & rebuild Cassandra clusters at will.

**Comment by genghisken** [comment]
Doing parallel tests of Cassandra at QUB and beginning to get an idea of how much space is required for each node.  Additionally, since we now have 10 million detections and 3 million nondetections in Cassandra (as of 2021-03-03), we are now getting an idea of how much space is required for each node (3.2GB per node at the moment).  Hence, currently, about 300 bytes per detection (including non detections).

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @genghisken has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2326757394/Cassandra+Report+for+Lasair+Cycle+3) for the A3.04 activity. At the above meeting it was agreed all tickets in A3.04 should be marked as done then closed.
