### ISSUE TITLE
Evaluate Cassandra Indexing (i.e. how the column groups aka tables are built)

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair#143]
* Can I just index by objectID - or do I need other indexes, like HTMID, etc (which will lead to table duplication)?
* If I integrate ElasticSearch does that affect how the columns are organised?

**Comment by genghisken** [comment]
I'm beginning to understand how indexes work in Cassandra.  I still have lots of questions (e.g. about spatial indexing and how cassandra clusters work).

**Comment by genghisken** [comment]
Held up until #93 and #118 where done.  We are now in a position to test this.  Initially we will index on objectId, but we might need to write the data more than once if we need indexing on other columns (e.g. JD).

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @genghisken has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2326757394/Cassandra+Report+for+Lasair+Cycle+3) for the A3.04 activity. At the above meeting it was agreed all tickets in A3.04 should be marked as done then closed.
