### ISSUE TITLE
Revise document and resubmit

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#145]
Comments have now been received from the reviewers, Cosimo Inserra and Raphael Shirley. We will make a version 1.1 incorporating their suggestions and formally resubmit

**Comment by tms-epcc** [comment]
Deliverable not yet complete. Waiting for Andy to complete the revised document and author's response then to send then to me so I can submit to the Exec for approval hence I am re-opening this issue.

**Comment by tms-epcc** [comment]
Deliverable published and available from https://lsst-uk.atlassian.net/wiki/spaces/HOME/pages/752156697/LSST+UK+Technical+Reports+Phase+B
