### ISSUE TITLE
Split Candidate attributes into usefulness: 1, 2, 3, 4

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair#15]
For example we could split the candidates table into `candidates_main` and `candidates_extra` and join the two tables on `candidateid` if/when the extra columns are required.

**Comment by genghisken** [comment]
Do we understand why the querying the split table is faster than querying the full table?  It's not a huge number of columns compared to what we're dealing with (e.g. Pan-STARRS schema - 91 columns).  Is it not just a matter of putting the right indexes in place?  Is it an InnoDB vs MyISAM issue?  Sounds like it's doing a full table scan rather than using an appropriate index.  Despite my reservations, I agree in principle that it's probably better to stick the instrument / project specific metadata in a separate table.  For ingest though, this means two inserts instead of one for every Kafka row.

**Comment by thespacedoctor** [comment]
Hi Ken, it was off the back of [this article](https://www.percona.com/blog/2009/09/28/how-number-of-columns-affects-performance/) that I made the suggestion to split the table. But I shared your scepticism ... so I did some tests! I can confirm that creating a 'lite' candidates table increase query performance by a factor of **~1.6**.

I created and populated the following (draft) table:

```sql
CREATE TABLE `candidates_main` (
  `objectId` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  `jd` double DEFAULT NULL,
  `candid` bigint(20) NOT NULL,
  `isdiffpos` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `nid` int(11) DEFAULT NULL,
  `field` int(11) DEFAULT NULL,
  `xpos` float DEFAULT NULL,
  `ypos` float DEFAULT NULL,
  `ra` double DEFAULT NULL,
  `decl` double DEFAULT NULL,
  `magpsf` float DEFAULT NULL,
  `sigmapsf` float DEFAULT NULL,
  `chipsf` float DEFAULT NULL,
  `magap` float DEFAULT NULL,
  `sigmagap` float DEFAULT NULL,
  `distnr` float DEFAULT NULL,
  `magnr` float DEFAULT NULL,
  `sigmagnr` float DEFAULT NULL,
  `sky` float DEFAULT NULL,
  `magdiff` float DEFAULT NULL,
  `fwhm` float DEFAULT NULL,
  `classtar` float DEFAULT NULL,
  `elong` float DEFAULT NULL,
  `nbad` int(11) DEFAULT NULL,
  `rb` float DEFAULT NULL,
  `ssdistnr` float DEFAULT NULL,
  `ssmagnr` float DEFAULT NULL,
  `sgmag1` float DEFAULT NULL,
  `srmag1` float DEFAULT NULL,
  `simag1` float DEFAULT NULL,
  `szmag1` float DEFAULT NULL,
  `sgscore1` float DEFAULT NULL,
  `ndethist` int(11) DEFAULT NULL,
  `distpsnr1` float DEFAULT NULL,
  `jdstarthist` double DEFAULT NULL,
  `jdendhist` double DEFAULT NULL,
  `scorr` float DEFAULT NULL,
  `objectidps1` bigint(20) DEFAULT NULL,
  `htmid16` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`candid`),
  KEY `htmid16idx` (`htmid16`),
  KEY `raidx` (`ra`),
  KEY `declidx` (`decl`),
  KEY `idx_magpsf` (`magpsf`),
  KEY `idx_candid` (`candid`),
  KEY `idx_objectid` (`objectId`),
  KEY `idx_rb_sgscore` (`sgscore1`,`rb`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

Query speeds on this table take ~60% of the time compared to the same query on the full candidates table.

I'll go ahead now and rate column usefulness.

**Comment by thespacedoctor** [comment]
Stale issue. Closing.
