### ISSUE TITLE
Define and document a few sample "big data" tasks

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#154]

**Comment by tms-epcc** [comment]
30/JUN/21
- @RoyWilliams and @tms-epcc agreed this is being dealt with in [Cycle-4](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair-lsst/67) under [Architecture Development](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair-lsst/69) dask experiment.

**Comment by tms-epcc** [comment]
This is the [feature set evolution ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2888663041/Feature+Set+Evolution+for+Lasair)
