### ISSUE TITLE
Write report on Solar System requirements

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#164]
The [report is written](https://lsst-uk.atlassian.net/wiki/download/attachments/758874134/lasair_solar_system_recommendations.pdf?api=v2) and is available from the [Lasair Phase B page](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/758874134/Lasair+Phase+B).

**Comment by tms-epcc** [comment]
14/JUL/21
- @RoyWilliams explained the [report is written](https://lsst-uk.atlassian.net/wiki/download/attachments/758874134/lasair_solar_system_recommendations.pdf?api=v2) and is available from the [Lasair Phase B page](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/758874134/Lasair+Phase+B) and so this can be closed
