### ISSUE TITLE
Add the option to make watchlists private

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair#17]

**Comment by RoyWilliams** [comment]
This is fixed on lasair-dev. A watchlist created by a user is visible only to that user. But also there is a new category of watchlist called anonymous that is visible to everyone, and the BLLac example is there. 
-- This is anonymous and public: https://lasair-dev.roe.ac.uk/watchlist/33/
-- This belongs to user roy and is private: https://lasair-dev.roe.ac.uk/watchlist/26/
If you read this, please test it by making your own watchlist.

**Comment by thespacedoctor** [comment]
I definitely can't see watchlist number 26 so authorisation seems to be working ... great.

When I create my own watchlist I don't see an option yet to specify whether or not I want to make the watchlist public/private.

**Comment by RoyWilliams** [comment]
OK I got rid of the anonymous user, and added an option to make a watchlist public. It defaults to private.

**Comment by RoyWilliams** [comment]
I got rid of Mr Anonymous, and instead put in an option to make your watchlist public.
