### ISSUE TITLE
Define Ansible Sherlock database deployment

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#180]

**Comment by genghisken** [comment]
Alas - I have to move this to "blocked".

I was refining my Ansible script when I decided to rebuild the Sherlock Database instance (so I could test repeatability).  Alas, OpenStack just won't play ball this week!  Destroyed my previous Sherlock Database install.  Tried to create a new one (as before, on the lasair-local network).  Got this error:

Error: Failed to perform requested operation on instance "Sherlock Database", the instance has an error status: Please try again later [Error: Build of instance faf8d9c5-1806-4039-8e76-376673a6a34e aborted: Failed to allocate the network(s), not rescheduling.].

**Comment by genghisken** [comment]
Was unable to deploy the database because of OpenStack problems.  This has been resolved for the time being.  Moving back to in progress.

**Comment by genghisken** [comment]
A generic script for deploying MySQL has been completed and tested. All functional now.
