### ISSUE TITLE
Read-only Kafka

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair#226]
Document how to set up Kafka to allow read-only access for anonymous users.

**Comment by gpfrancis** [comment]
Config files in branch "issue226" of narcissus.

General description:

1) Have 2 listeners - SASL_PLAINTEXT for internal/inter-broker operations; PLAINTEXT for external read-only access.
2) Use SCRAM-SHA-256 as the SASL mechanism.
3) Create a super user "admin" - see kafka_server_jaas.conf 
4) Set an ACL to allow read access for anon users to topics starting with "lsst_":
`ResourcePattern(resourceType=TOPIC, name=lsst_, patternType=PREFIXED)`: 
 	(principal=User:*, host=*, operation=READ, permissionType=ALLOW)

**Comment by tms-epcc** [comment]
30/JUN/21
-RoyW and TerryS agreed this can be closed
