### ISSUE TITLE
How to query it?

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#230]
How to take a reasonable astro query and run it against cassandra?

**Comment by tms-epcc** [comment]
As agreed at the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), @genghisken has written a [report ](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2326757394/Cassandra+Report+for+Lasair+Cycle+3) for the A3.04 activity. At the above meeting it was agreed all tickets in A3.04 should be marked as done then closed.
