### ISSUE TITLE
password reset not working 

### ISSUE THREAD

**Issue by leannep** [lsst-uk/lasair#238]
I've tried to change my password 3 times, but each time when I try to log on after changing my password, it tells me that my new password and username don't match. I've tried with and without using a pwd manager.

**Comment by RoyWilliams** [comment]
Hi Leanne
Sorry about this difficulty. Can I ask which system you are using, old or new? Did you do the steps below?
Roy

You have an account on the old system lasair.roe.ac.uk
That has been migrated to the new system lasair-iris.roe.ac.uk
The user name is leanne and email is leanne.guy@lsst.org

To reset the password go here for the old system
https://lasair.roe.ac.uk/accounts/password_reset/
or here for the new system
https://lasair-iris.roe.ac.uk/accounts/password_reset/

Enter the email as leanne.guy@lsst.org
When you get the email, click on the link and enter your password twice
When you log in use your username is leanne

**Comment by leannep** [comment]
Hi Roy, 
Pretty sure it was ROE.  I just tried on the iris system and I get the same.  
I reset my passowrd successfully but when I go to log on again it give me "Your username and password didn't match. Please try again."

**Comment by leannep** [comment]
Thanks Roy
