### ISSUE TITLE
Conesearch not working with object name

### ISSUE THREAD

**Issue by mnicholl** [lsst-uk/lasair#242]
On Lasair-iris I encounter an error when trying to do a conesearch by objectId:

e.g. I put 'ZTF21abbzhvg' into the search box, and get the message:

cannot parse ZTF21abbzhvg
No objects found in the specified cone.

Searching by TNS ID does not return an error, but still doesn't find the object:

AT2021mth not found in TNS
No objects found in the specified cone.

**Comment by RoyWilliams** [comment]
I have now enhanced the conesearch by allowing ZTF identifiers to be converted to a link.

The TNS bug was more subtle, but I have fixed a problem, and made a test for the same failure happening again. Should be OK, let me know if further problems.
