### ISSUE TITLE
Extremely slow I/O performance from default OpenStack VM volumes

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair#245]
I created 5 Cassandra instances, each of which has a 1TB "volume" associated with each instance.  I presume these are of the "Cinder" type.  These volumes - perhaps because of the amount of stack that needs to be unravelled to communicate with them, are staggeringly slow.  I transferred a 25GB tar file to the the filesystem from another node.  Extracting the tar file (which is NOT gzipped) took 25 minutes.

It takes an HOUR to compress a similar sized file with gzip on a one of these VMs (8 vCPUs & 10GB of memory).  It's actually much quicker to transfer the files off the cluster uncompressed.

Can anyone give us any advice about what we might be doing wrong?  Surely this can't be the norm for Somerville?  Maybe the new hardware will fix this...  Or is this a fundamental problem with the OpenStack I/O layer?  If the latter, this will not be easy to mitigate, even with NVME SSD.

Note that this problem pre-dates any recent power outages - it's always been like this - I've just finally lost patience with it!

Additionally, dealing with files on a mounted CephFS partition seems to be much quicker, though mounting common CephFS filesystems is a design antipattern for Cassandra (all I/O should be local to the VM).  Additionally installation of the CephFS drivers creates a python conflict on my systems.  (They are python 2 only - but all my systems are python 3.)

**Comment by markgbeckett** [comment]
Mark H has checked the Ceph system, and confirmed it looks healthy with no reported issues. Mark has asked for details of the file-system/ disk format that has been used for the Cassandra volumes.

**Comment by genghisken** [comment]
Here's a very simple test.  Count the lines of a 10 million line CSV file.  It's a serial operation so should be fast.

On laptop (admittedly SSD):
```
(base) kws::mp148918 { ~/lasair/cassandra/load_old_data }-> time wc -l dump00.out 
 10000001 dump00.out

real	0m6.630s
user	0m4.568s
sys	0m1.621s

```

On local linux box (spinning disk) at QUB:
```
atls::db4 { ~/lasair }-> time wc -l dump00.out 
10000001 dump00.out

real	0m2.365s
user	0m0.353s
sys	0m2.011s
```

On CephFS from lt-head in the lasair network on Somerville - 10 to 20x slower than QUB hardware (spinning disk):
```
ubuntu@lasair-head:/mnt/cephfs/roy/oldlasairdump$ time wc -l dump00.out 
10000001 dump00.out

real	0m40.054s
user	0m0.557s
sys	0m3.635s
```

On Cassandra node 2 - 270x slower than QUB hardware!:
```
ubuntu@cassandra-node-2:~$ time wc -l dump00.out 
10000001 dump00.out

real	9m11.786s
user	0m0.688s
sys	0m5.159s
```
**NINE Minutes!!**  Yikes! Same time for all the other Cassandra nodes.

The results from the sherlock nodes are also very interesting...

Sherlock node 1 (slow-ish):
```ubuntu@sherlock-node-1:~$ time wc -l dump00.out 
10000001 dump00.out

real	1m12.899s
user	0m0.393s
sys	0m2.529s
```

Sherlock node 2 (blisteringly fast - what I expected in the first place):
```
ubuntu@sherlock-node-2:~$ time wc -l dump00.out 
10000001 dump00.out

real	0m1.916s
user	0m0.412s
sys	0m1.503s
```

Note that if I now go back to sherlock node 1, the count only takes 3 seconds (hence something must be cached).  But the Cassandra nodes are consistently slow all the time.

As for the file system/ disk format that has been used for the Cassandra volumes - I've no idea. It's whatever is the default when adding a new VM via the OpenStack web interface.
![openstack_volume](https://user-images.githubusercontent.com/5502468/134704619-4db069f9-b8ab-43cb-9dd7-bb253f2f1329.png)

**Comment by astrodb** [comment]
@genghisken - Can you clear your disk cache on the spinning disk you tested at QUB? That result looks suspiciously like the file was cached. (I'm guessing that, since what I see from a completely separate node on our CephFS, running your exact command on the same file produces the results below):

`root@vvv-iris:/home/ubuntu# cd /mnt/cephfs/roy/oldlasairdump
root@vvv-iris:/mnt/cephfs/roy/oldlasairdump# time wc -l dump00.out
10000001 dump00.out

real    0m21.086s
user    0m0.537s
sys     0m3.043s
root@vvv-iris:/mnt/cephfs/roy/oldlasairdump# time wc -l dump00.out
10000001 dump00.out

real    0m2.296s
user    0m0.344s
sys     0m1.949s
`

**Comment by astrodb** [comment]
While I ran that command on the CephFS system, I watched the IO figures for the storage system, and they looked reasonable:

```
  io:
    client:   347 MiB/s rd, 2.6 KiB/s wr, 131 op/s rd, 1 op/s wr
```

That's a decent throughput for a single threaded command.

**Comment by astrodb** [comment]
All subsequent runs of that command take ~2s, so it's definitely getting cached.

I added a volume onto the same test server, formatted it in ext4, and copied dump01.out over to it. Copy time wasn't great, but it wasn't horrible either:
```

root@vvv-iris:/mnt/cephfs/roy/oldlasairdump# time cp dump01.out /mnt/ken-test/

real    0m25.808s
user    0m0.000s
sys     0m9.596s
```

That's around 290MBps.

Running the 'wc' test again is producing an uglier result, but nowhere near as bad as your Cassandra nodes:

```
root@vvv-iris:/mnt/ken-test# time wc -l dump01.out
10000001 dump01.out

real    3m21.829s
user    0m0.566s
sys     0m4.083s
root@vvv-iris:/mnt/ken-test# time wc -l dump01.out
10000001 dump01.out

real    0m6.350s
user    0m0.427s
sys     0m1.848s
```
Like before, then second run is obviously cached and runs quick.

**Comment by genghisken** [comment]
QUB machine again.  Fairly sure the disk cache was cleared.  Obviously 2nd time much quicker. But 1st time still 7s.
```
atls::db4 { ~/lasair }-> time wc -l dump00.out 
10000001 dump00.out

real	0m6.940s
user	0m0.488s
sys	0m2.202s
atls::db4 { ~/lasair }-> time wc -l dump00.out 
10000001 dump00.out

real	0m1.719s
user	0m0.356s
sys	0m1.363s
atls::db4 { ~/lasair }-> 
```

At QUB the output of lsblk is below. The file is on sdb1 in /export/raid
```
atls::db4 { ~/lasair }-> lsblk
NAME                     MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                        8:0    0 111.3G  0 disk 
├─sda1                     8:1    0   250M  0 part /boot/efi
├─sda2                     8:2    0     1G  0 part /boot
└─sda3                     8:3    0   110G  0 part 
  ├─centos_db4-root      253:0    0    50G  0 lvm  /
  ├─centos_db4-swap      253:1    0     4G  0 lvm  [SWAP]
  └─centos_db4-localdisk 253:2    0    56G  0 lvm  /localdisk
sdb                        8:16   0  25.5T  0 disk 
└─sdb1                     8:17   0  25.5T  0 part /export/raid
sdc                        8:32   0  10.5T  0 disk 
└─sdc1                     8:33   0  10.5T  0 part /ssdraid0
```

Output of lsblk on Cassandra node 2 is:
```
ubuntu@cassandra-node-2:~$ lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
vda     252:0    0  1000G  0 disk 
├─vda1  252:1    0 999.9G  0 part /
├─vda14 252:14   0     4M  0 part 
└─vda15 252:15   0   106M  0 part /boot/efi
```

Checked Cassandra node 2 again today.  Still terrible, but of course improved once cached.
```
ubuntu@cassandra-node-2:~$ time wc -l dump00.out 
10000001 dump00.out

real	9m31.302s
user	0m0.595s
sys	0m5.138s
ubuntu@cassandra-node-2:~$ time wc -l dump00.out 
10000001 dump00.out

real	2m41.096s
user	0m0.654s
sys	0m5.331s
ubuntu@cassandra-node-2:~$ time wc -l dump00.out 
10000001 dump00.out

real	2m7.050s
user	0m0.622s
sys	0m4.768s
ubuntu@cassandra-node-2:~$ time wc -l dump00.out 
10000001 dump00.out

real	1m40.695s
user	0m0.577s
sys	0m4.556s
```

Also randomly tried another cassandra node.  Also pretty bad 1st time round.  So it's not a fluke. They're all this bad.
```
ubuntu@cassandra-node-4:~$ time wc -l dump00.out 
10000001 dump00.out

real	5m56.511s
user	0m0.753s
sys	0m5.255s


ubuntu@cassandra-node-4:~$ lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
vda     252:0    0  1000G  0 disk 
├─vda1  252:1    0 999.9G  0 part /
├─vda14 252:14   0     4M  0 part 
└─vda15 252:15   0   106M  0 part /boot/efi
```

**Comment by astrodb** [comment]
The disk on your QUB machine is part of a RAID array, correct? What's the RAID look like (version, raid card with cache?)

Can you try creating a volume and attaching it to your Cassandra node, then format it as ext4, mount it, and run the tests again? I'm curious to see if that gives a different performance. The block device those nodes are using appears to be the default from the OS image you used, and it also houses and runs the OS which could be interfering with things. 


Things do seem a lot slower coming off the block storage than they should, but I can't see any issues with the storage system itself. I ran these same tests on a completely separate and non cloud machine and they went quick. I also tried them on a separate machine with a different CephFS system, and those were equally quick. So something is definitely wrong here, but I'm not sure where exactly...

**Comment by astrodb** [comment]
I've gone through a number of checks, and the ceph system, ceph nodes, and network all seem happy and healthy. I don't see any obvious issues on the hypervisors either, and the tests I've run were on an instance running on a different HV than your instances, so we can rule out a problem there. 

I am seeing an odd error in the logs on the OpenStack head server which indicates a problem on one of the underlying docker containers. I'll need to dig into those next and see if something is going wrong within the daemons.

**Comment by astrodb** [comment]
Card was replaced, but the problem is persisting. I'll need to dig deeper into the ceph side of things to see what's going on.

**Comment by astrodb** [comment]
We are seeing random read errors coming from all the disks on ceph1, which is likely a sign that either the disk controller is faulty or there is an issue with the PCI bus on the motherboard. These errors weren't seen prior to the new network card installation, but they are certainly causing problems now with the IO rate.

We'll need to discuss how best to solve the problem. The first option is to source a replacement disk controller and swap out the current one, hoping this fixes the problem. The second option is to harvest a controller out of one of the other ceph nodes (likely the ones hosting the cephfs system), but we need to know who this would impact (since it would make the cephfs system vulnerable to data loss in the event of a node failure). The third option is to offload the data from all the disks on ceph1, removing it from the cluster will improve the IO, but it will mean the system is vulnerable to data loss if another node fails.

**Comment by astrodb** [comment]
We harvested a replacement disk controller from another machine and the disk errors on ceph1 have disappeared. 

But I've rerun the tests (same commands as above, on a vm using a mounted volume), and the slow performance is still there. So it looks like neither the network interface, nor the disk controller, on ceph1 are the source of the problem. Which means investigations will need to continue...

**Comment by markgbeckett** [comment]
As discussed, we have paused work on this investigation, awaiting new hardware. We will re-test performance on new hardware and continue investigation if still seeing issues.

**Comment by astrodb** [comment]
I'm afraid to say it, but the performance on the new kit doesn't look any better for these particular tests:

`root@vvv-somerville2:/data/test# time wc -l dump00.out
10000001 dump00.out

real    1m55.295s
user    0m0.476s
sys     0m5.812s
root@vvv-somerville2:/data/test# time wc -l dump01.out
10000001 dump01.out

real    1m58.783s
user    0m0.461s
sys     0m6.213s
root@vvv-somerville2:/data/test# time wc -l dump00.out
10000001 dump00.out

real    1m59.006s
user    0m0.503s
sys     0m5.934s
root@vvv-somerville2:/data/test# time wc -l dump01.out
10000001 dump01.out

real    2m3.150s
user    0m0.397s
sys     0m6.494s
`

My database query tests, file copy tests, and other file IO tests indicate an improvement on the new kit. So I'm not sure why these tests with counting lines in a file go so slow, but I think it must be inherent in the task.

**Comment by markgbeckett** [comment]
Is this something we can raise with StackHPC for advice?

**Comment by astrodb** [comment]
We can ask them next week, but I'm not sure if there's much they can do about it. My guess is this is due to something inherent in the way the files are stored by Ceph against how the 'wc' command calls and accesses them.

**Comment by markgbeckett** [comment]
Believed to be a symptom of high-latency file systems, which needs to be worked around in software. 

One outstanding anomoly is that O/S disks do not seem to have same slowdown as user-created volumes, even though they are both set up on Ceph cluster. @gpfrancis is investigating.

**Comment by markgbeckett** [comment]
@gpfrancis has confirmed the anomoly with O/S disks is an error in the tests. Disks perform as expected.

**Comment by markgbeckett** [comment]
Based on evidence collected, we do not believe this is a bug or issue with Somerville, but a weakness of virtualised file systems. As such, the only way to work around the performance issue is in (application) software.
