### ISSUE TITLE
sherlock crossmatch with no rank

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#28]
Many times an object has multiple crossmatches, where one has a rank=1 and the others have rank=NULL. What is happening? Example below.

```
mysql> select catalogue_object_id, rank, rankScore from sherlock_crossmatches where transient_object_id = 3250866;
+--------------------------------+------+--------------------+
| catalogue_object_id            | rank | rankScore          |
+--------------------------------+------+--------------------+
| 1226849/00341665+0226038/00341 |    1 | 1010.3234574164297 |
| 1226849                        | NULL | 1010.3234574164297 |
| 00341665+0226038               | NULL | 1010.3234574164297 |
| 00341663+0226037               | NULL | 1010.3234574164297 |
| 1237678433792229555            | NULL | 1010.3234574164297 |
+--------------------------------+------+--------------------+

mysql> select count(*) from sherlock_crossmatches where catalogue_object_id is not null and rank is null;
+----------+
| count(*) |
+----------+
|  1493122 |
+----------+
```

**Comment by thespacedoctor** [comment]
Hi Roy, this change is a result of an update to the Sherlock crossmatch ranking algorithm.

![](https://farm2.staticflickr.com/1950/45516628802_d586a149f1_o.png)

In many cases numerous sources from multiple catalogues are matched against the same transient. These matches are often different sources, but in some cases the same astrophysical source is listed across many catalogues with differing IDs.

The first job of the (new) ranking algorithm is to attempt to group together catalogue entries of the single sources. Once this grouping is done the matched sources need to be ranked in order of likelihood of being correctly associated with the transient.

The metrics that can are used to rank multiple potential associations are:

- Association Type ("AGN", "CV", "NT", "SN", "VS", "BS" ...)
- Physical Separation between source and transient locations
- Source Catalogue Accuracy (some catalogues are better than others)
- Angular Separation between source and transient locations

After the results are grouped into distinct astrophysical sources, a merged 'best-of' parameter-set is generated for each group. The best distance estimate/measurement is selected, all reported magnitudes are combined, the closest coordinate set to the transient location is used and the smallest transient-source angular separation converted to a physical distance separation.

If multiple classification are given for the group then the most accurate classification is selected from this ordered list: "AGN", "CV", "NT", "SN", "VS", "BS". For example if there are 3 entries for a distinct source with classifications "AGN", "NT" and "VS" then "AGN" is selected as the best classification.

Merged, duplicated-source rows get the 'rank' parameter filled but the single sources combined into these merged entries are still recorded with the 'rank' parameter set to *null* and the 'merged_rank' parameter filled to show which merged entry they belong to.

In the example quoted above you will hopefully find the top row has rank = 1, merged_rank = null and the rest of the rows that make up that merged recored will have rank = null, merged_rank = 1.

Lasair need only display the rows with rank != null.
