### ISSUE TITLE
ZTF photometry not the same as ATLAS - and ATLAS is correct

### ISSUE THREAD

**Issue by smarttgit** [lsst-uk/lasair#30]
This is very odd : 

this ZTF object
https://lasair.roe.ac.uk/object/ZTF18abhqeds

is  the same object as ATLAS  
https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1222824041134943200/

But the ZTF lightcurve is totally different  - it is bright and flat 120 days ! But that is not believable. Don't understand what is going on here. The ATLAS data show no bright object after the first detection

**Comment by genghisken** [comment]
Odd indeed.  But the issue goes back to ZTF I think. Same lightcurve on MARS.
https://mars.lco.global/20501975/

**Comment by smarttgit** [comment]
As Ken sees the same in MARS, we need to alert ZTF. Presume this repo is public - we can point Matthew to it.

**Comment by RoyWilliams** [comment]
From: Eric C. Bellm [ecbellm@uw.edu]
Sent: 20 November 2018 7:07 PM
To: Roy Williams
Cc: Graham, Matthew J.
Subject: Re: wacko object in ZTF

Hi Roy,

It looks like the object has an underlying counterpart in the reference image: 
distnr	0.155174
magnr	17.062

So the difference image photometry (magpsf) needs to be corrected to add the flux from the reference counterpart to get the appropriate DC magnitude.  Note that the reference flux will be different in different fields (or even different readout quadrants of the same CCD) which accounts for the offset you see between the two fields--the magnr value is 15.742 in the other field.

Best regards,
Eric

On Tue, Nov 20, 2018 at 8:50 AM Roy Williams <roy@roe.ac.uk> wrote:
Hi Matthew and Eric
Here is a strange object
https://lasair.roe.ac.uk/object/ZTF18abhqeds/

The magnitudes bounce up and down in a slightly unbelievable way. For example these two candidates belong to this object, the r magnitude changes by 1.5 in 2 minutes.

2458400.728     2018-10-09 05:27:53     r       16.109 ± 0.041  646227705115010014      
2458400.726     2018-10-09 05:25:53     r       17.676 ± 0.110  646226306215010000

One is on field 546 and the other on field 547.
Roy

**Comment by smarttgit** [comment]
Ah, of course ! The stamps are  REF - TARGET - DIFF (from left to right; I missed that, we usually have TARGET - REF - DIFF). 

And this flux is negative - which is of course correct. The negative object flag is set : 
isdiffpos = f 

So, we need a way to flag these as -ve detections. We can treat them the same, but just plot them as negative. 

All OK - I understand now. I think we can keep the plots the same, all we do is plot in the isdiffpos=f points in a different symbol.  But we need to make all the symbols a little larger to see it. 
For example, we plot the -ve values in ATLAS as large transparent diamonds.

**Comment by smarttgit** [comment]
Need to plot these -ve mags in a different way - they are still coming through
