### ISSUE TITLE
Minor niggles and bugs 

### ISSUE THREAD

**Issue by smarttgit** [lsst-uk/lasair#31]
Conesearch links : 
Move this up to the bullet points - it's too far down 

The NED link is broken !

Add a crossmatch link to Vizier - searches multiple catalogues  
http://vizier.u-strasbg.fr/viz-bin/VizieR

The 2nd bullet point is often missing words. e.g. 
https://lasair.roe.ac.uk/object/ZTF18acqwdla/
Says 
 "Classified as SN at distance arcsec."
 "None"

Should say 
"Classified as SN at 2.77 arcsec distance from SDSS DR12 galaxy ."

and why is the third bullet point "None" - this is where the info on the host galaxy should go

All the quantitative info is in the Sherlock table. Just need to propagate it up here

**Comment by RoyWilliams** [comment]
Conesearch links moved up.
NED link fixed.
Vizier link is difficult -- will defer
Should be no more funny stuff with the annotation. For the object that you quote above, there actually is no sherlock:
```
mysql> SELECT o.primaryId, o.ncand, o.ramean, o.decmean, o.glonmean, o.glatmean, 
s.classification, s.annotation, s.separationArcsec  FROM objects AS o LEFT JOIN
 sherlock_classifications AS s ON o.primaryId = s.transient_object_id 
WHERE stale != 1 AND o.objectId = "ZTF18acqwdla"
*************************** 1. row ***************************
       primaryId: 9733279
           ncand: 12
          ramean: 106.47265259166666
         decmean: 12.892961283333333
        glonmean: 202.987227121
        glatmean: 8.99897625286
  classification: SN
      annotation: NULL
separationArcsec: NULL 
```
