### ISSUE TITLE
Objects in `objects` table with fewer than 3 detections

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair#36]
For an object to make it into the objects table it needs to have 3 or more detections in the candidates table, however there are 100,593 source in the objects table with < 3 detections:

```sql
select * from objects where objectId = "ZTF19aahjeky";
> 100593
```

Does anyone know why this is?

**Comment by genghisken** [comment]
I think Roy started running a script a few weeks ago when we were talking about reducing the detection threshold. This probably left some data in the objects table. (Roy can confirm.)

**Comment by RoyWilliams** [comment]
I see an object with <3 candidates. I think I made a change to the code and it ran that way for a few days .... let me try to zap them
`mysql> select count(*) from objects where objectId="ZTF19aahjeky";
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)

mysql> select count(*) from candidates where objectId="ZTF19aahjeky";
+----------+
| count(*) |
+----------+
|        2 |
+----------+
`

**Comment by thespacedoctor** [comment]
Sorry copy and pasted the wrong query in comment one.

```sql
select * from objects where objectId = "ZTF19aahjeky";
> 100593
```

should have been

```sql
select * from objects where ncand < 3;
> 100593
```

**Comment by RoyWilliams** [comment]
All deleted now. Lets try to run these sanity tests regularly. 
Issue 32 is "Sanity checks on object table"

**Comment by thespacedoctor** [comment]
Super - thanks Roy:

```sql
select * from objects where ncand < 3;
> 0
```
