### ISSUE TITLE
Movers in the Objects list

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair#37]
While trying to understand the ZTF differencing imaging process I did some digging in the database and discovered ~3400 solar-system bodies in our `objects` table. 

```sql
SELECT 
    c.objectId, c.ssnamenr , count(*)
FROM
    candidates c,
    objects o
WHERE
    ssnamenr IS NOT NULL
    and ssnamenr != "null"
        AND c.objectId = o.objectId
        AND c.ssdistnr = 0
GROUP BY c.objectId;
```

Most of these are related to issue #36 but occasionally there are 3 or more detections of an SS-object spatially close together (within the 1.5 arcsec ZTF matching radius) on one night. This allows the associated candidates to pass the '3 or more' threshold and make it into the objects table.

Sherlock will classify these as 'ORPHANS' and outgest them to the PESSTO Marshall, so a potentially disruptive bug.

The fix would be to:

1. Remove these ~3400 vermin from the objects table, and
2. a check on the `ssdistnr` value for candidates when evaluating whether future candidates make it to the objects table. `ssdistnr != 0` should be enough.

There's another situation where movers might cause trouble. When an *unknown* slow-mover is first detected it will be injected into the alert stream with no ss-object match. These sources may get promoted to the `objects` table. Later whenever an orbit is calculated for the object it will get assigned an MPC ID - we will have to do some bookkeeping to then retrospectively remove these from our `objects` table. You would use the query above to detect such objects. For ZTF it is probably not an issue, but in the age of LSST my guess is that it will be. It's an easy catch so we could just code it up now.

**Comment by thespacedoctor** [comment]
Now urgent to remove and excluded these SSObjects from the objects list - one was observed by ePESSTO:

https://lasair.roe.ac.uk/object/ZTF19aailrrd/

I'll code in a double check with my ePESSTO Marshall outgest.

**Comment by tms-epcc** [comment]
15/SEP/21
- as explained by @RoyWilliams this was done and hence ticket can be closed.
