### ISSUE TITLE
Historical Detections Question

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair#38]
I have a query about historical detections that hopefully someone can answer.

A crossmatching radius of 1.5 arcsec and a look-back time of 30 days is used to match historical difference-image detections with Alert Stream candidates. The only filtering criterion for historical detections is it must have S/N > 5𝜎 , therefore it's likely that Alert Stream candidates will have historical detections that have *not been seen* in the stream before because the filtering criteria for candidates are stricter than those for their historic detections.

Does the method being used to ingest the Avro packet content into the database allow for the capture of these previously unseen historical detections?

**Comment by thespacedoctor** [comment]
I've done some investigating on this question and we are **definitely missing detections**.

Taking [ZTF19aafmytc](https://lasair.roe.ac.uk/object/ZTF19aafmytc/) as an example. You can find the source plotted in Lasair [here](https://lasair.roe.ac.uk/object/ZTF19aafmytc/) and in the MARS broker [here](https://mars.lco.global/28982473/#).

Both brokers seem to be plotting the same data which includes:

- 5 detections, and
- 13 non-detections 

**BUT ...**

Viewing the [latest AVRO packet for the source](https://s3-us-west-2.amazonaws.com/ztf-alert.lco.global/2019/02/08/768543036215015007.avro) (curtesy of the Mars broker) I find the `candidate` schema contains the latest detection of the source and `prv_candidates` schema contains 19 records. Combining the two schema we have:

- 12 detections, and
- 8 non-detections

So many of the detections in the `prv_candidates` schema are being mis-interrupted as non-detections by both Lasair and MARS.

Here's the lightcurve plotted with the correct interruption of the `prv_candidates` records.

![](https://farm8.staticflickr.com/7915/46341607624_41b0b37be9_o.png)

Unfortunately these missing detections aren't in the database. Are we archiving the original avro packets so we can recover these lost detections? Or maybe we should just cut our losses and fix the code from here on in?

**Comment by thespacedoctor** [comment]
FYI the ZTF TNS report for this source has first detection at 58508.54 and last non-detection at 58494.54 which ring true with the plot above (if you neglect the brighter r-band limits between 58500-58507). 

<https://wis-tns.weizmann.ac.il/object/2019agc>

**Comment by RoyWilliams** [comment]
Dave -- the schema document says "The prv_candidates field contains an array of one or more previous subtraction candidates at the position of the alert. These are obtained by a simple cone search at the position of the alert candidate on the last 30 days of history."

Are you suggesting that (a) Lasair and MARS have been dropping packets, or (b) that ZTF is not sending us all of the candidates? If they have been sending, and we have been receiving, how can we have missed them?

Maybe you should direct your question to Eric Bellm and Mario Jurek?

**Comment by thespacedoctor** [comment]
The issue is to do with the different filtering thresholds for 'alert candidates' and 'historical candidates'. There are stricter filters on alert candidates (i.e. those candidates that trigger an alert and get injected into the alert stream) than on historical candidates.

An individual object's alert candidates (candidates that have triggered an alert) are the best sub-set of its historical candidates, therefore an object will usually have a few historical candidates that have never triggered an alert and therefore will only ever be found in the `prv_candidates` schema.

See page 60 bullet 6 for the ZTF deliverables doc:

http://web.ipac.caltech.edu/staff/fmasci/ztf/ztf_pipelines_deliverables.pdf

I'll raise the issue in slack with eric et al.

**Comment by RoyWilliams** [comment]
The handling of the prv_candidates section of the alert is here:
https://github.com/lsst-uk/lasair/blob/master/src/alert_stream_ztf/bin/ingestStream.py#L118

It looks for those entries that have no candidate ID, and assumes that these represent non-detections. What should we be doing instead? It is not clear to me after reading the Deliverables document.

**Comment by thespacedoctor** [comment]
Yes that's good for picking out the non-detection:

```python
detections[:] = [p for p in prv_array if d["candid"]]
print len(detections)
```

This gives us out 8 non-detections in the last 30 days.

But reverse that logic to get the detections in your `prv_array` 

```python
detections[:] = [p for p in prv_array if d["candid"]]
print len(detections)
```

Gives 11 detections for ZTF19aafmytc (+1 in the candidates schema = 12 detections). We have only 6 of these 12 detections in the database.

**Comment by thespacedoctor** [comment]
Yes that's good for picking out the non-detection:

```python
nondetections[:] = [p for p in prv_array if d["candid"]]
print len(nondetections)
```

This gives us out 8 non-detections in the last 30 days.

But reverse that logic to get the detections in your `prv_array` 

```python
detections[:] = [p for p in prv_array if d["candid"]]
print len(detections)
```

Gives 11 detections for ZTF19aafmytc (+1 in the candidates schema = 12 detections). We have only 6 of these 12 detections in the database.

**Comment by thespacedoctor** [comment]
Suspicions confirmed by Eric Bellem:

> If the `magpsf` record, etc. in `prv_candidates` is not null it should be interpreted as a detection, whether or not an alert was previously issued for that `pid`

https://ztf-broker-ops.slack.com/archives/CAZK6TKU3/p1550083616011000

**Comment by smarttgit** [comment]
This is big issue !! Our biggest so far to fix 

Clearly we're missing these detections - as Dave notes, the issue is that an alert is triggered when various strict criteria are met, but previous candidates may be perfectly fine 5 sigma detections that fail some other requirement. These should **_definitely_** be interpreted by us a detection. 

Mars is missing them too - it seems to know about them, but interprets them as upper limits. 

High priority to fix 
1. Highest priority is to fix from now, so we have it correct from now onwards (this should pull in last 30 days)
2. Lower priority to see if we can go back an retrieve all. 

Let's deal with the first as high priority

**Comment by RoyWilliams** [comment]
I made the changes. On the test-rig, I deleted all the candidates, then read in all 35000 from Feb 10. You can see there are plenty of earlier candidates came in alongside. I think/hope the ingestion will work properly now. Lets wait for a clear night at Palomar.

Historical candidate is inserted here
https://github.com/lsst-uk/lasair/blob/master/src/alert_stream_ztf/bin/ingestStream.py#L158

select nid,count(*) from candidates_test group by nid;
+------+----------+
| nid  | count(*) |
+------+----------+
|  740 |     2751 |
|  741 |     9056 |
|  748 |     2203 |
|  749 |     2184 |
|  750 |     1106 |
|  751 |     7299 |
|  752 |     4106 |
|  753 |     8694 |
|  754 |     8151 |
|  755 |     9546 |
|  756 |     8227 |
|  757 |    10194 |
|  758 |      462 |
|  759 |     2639 |
|  760 |     4535 |
|  768 |     6542 |
|  769 |     7603 |
|  770 |    34703 |
+------+----------+
18 rows in set (0.13 sec)

**Comment by thespacedoctor** [comment]
Excellent - thanks Roy!

Looking back at our example object [ZTF19aafmytc](https://lasair.roe.ac.uk/object/ZTF19aafmytc/) you can see the lightcurve is much more filled out:

![](https://farm8.staticflickr.com/7892/47133114081_7f19040021_b.jpg)

And the table of detections/non-detections reveals 6 detections with images and 7 without images:

![](https://farm8.staticflickr.com/7804/40168085403_efe6edaeff_b.jpg)

Those without images are the detections we were previously missing. They don't have images as they were never injected into the alert stream as lead-candidates and therefore we didn't receive FITS stamps for them. It seems most of the missing detections are from the start of the lightcurve and therefore very important for constraining explosion epochs and rise times.

**Comment by RoyWilliams** [comment]
I got rid of the broken links for images. There are three kinds of candidates listed on the objects page
-- Primary candidate, from the main section of the avro packet, with stamp images. It has candid not null and ndethist > 0.
-- Nondetections, from the prv section of the avro packet. No stamp images and no candid. Stored in a separate table.
-- Historical candidate, from the prv section of the avro packet, no stamp images, has a candid but ndethist is None.

**Comment by tms-epcc** [comment]
06/JUL/22
- @RoyWilliams reported that scalability requires a finite light curve therefore this will not be dealt with.
