### ISSUE TITLE
Get Sherlock running on all ZTF objects to annotate all sources with context info

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair#4]

**Comment by smarttgit** [comment]
https://lasair.roe.ac.uk/object/ZTF19aadyppr/

Seems to be problem in Sherlock classifying this - did not get SN designation and it's in M51 !!!

**Comment by genghisken** [comment]
Sherlock did NOT run because there are only 2 points on the lightcurve.  Sherlock runs on the 'objects' table, and this object hasn't made it there yet (need another point).  The webapp cone search runs on the candidates table, not the objects table at the moment.

**Comment by thespacedoctor** [comment]
Note the Mars broker only has 2 data points also. To reiterate what Ken said, our current workflow:

1. detections flow into Lasair 'candidates' table
2. if 3 or more 'candidates' are matched together, the source gets prompted to the Lasair 'objects' table
3. sherlock runs on the objects table
4. SN/NT/Orphans get outgested to the PESSTO Marshall

We were caught out at step 2. 

Our problem here is that we were *late in recognising a young transient event in a nearby galaxy*, so a solution might be to have a parallel workflow:

1. detections flow into Lasair 'candidates' table
2. if **2** or more detections are matched, sherlock is run
3. if sherlock matches to a nearby galaxy (< 120Mpc?), the source is promoted to the object table

Or alternatively, and a lot easier to implement, just reduce the threshold for candidates to make it to the objects table from 3 to 2 detections.

**Comment by thespacedoctor** [comment]
This has been done. Issues is not connected to any project board so closing.
