### ISSUE TITLE
NED link search needs a larger fixed radius 

### ISSUE THREAD

**Issue by smarttgit** [lsst-uk/lasair#48]
Easy fix 

On each object page there is a link to NED to allow users to check the Sherlock cross-match. 

The link provides a search radius of only 4.8". Hence often null result returned. 

Can you increase this to 2 arcmins = 120 arcsecs. 

Even better if could have a separate link to NED that had a box for user input e.g. 

NED search : click here to search [free text box] arcsecs around the transient position 

And default that to 60 arcsecs but allow user to choose.

**Comment by RoyWilliams** [comment]
I changed it to 2 arcmin. Will do the other suggestion at a later time.

**Comment by tms-epcc** [comment]
06/JUL/22
-  @RoyWilliams reported that this has been changed to 2 arcmin and works
