### ISSUE TITLE
Short list candidate technologies for blob store

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#58]
Based on requirements, platformed on Openstack, identify a few promising technologies.
One should be standard Unix filesystem.

**Comment by RoyWilliams** [comment]
Here are four technologies. Maybe there are more. I wonder what our Gaia colleagues are using.

Cassandra: http://cassandra.apache.org/
Automatic replication and cluster scaling.

MinIO: https://min.io/
MinIO is High Performance Object Storage released under Apache. It is API compatible with Amazon S3.

RADOS: https://docs.ceph.com/docs/bobtail/rados/
Ceph’s RADOS Object Store is the foundation for all Ceph clusters.  Being implemented by Dave Morris for ESCAPE project

Swift: https://docs.openstack.org/swift/latest/
OpenStack Swift is a highly available, distributed, eventually consistent object/blob store.

**Comment by Zarquan** [comment]
> Being implemented by Dave Morris for ESCAPE project
Not in the plan at the moment.

**Comment by RoyWilliams** [comment]
Oh sorry Dave, I'm mixing up Rucio and Rados ...

**Comment by RoyWilliams** [comment]
Gareth Roy Terry met 5 Feb
Actions:

Email on Requirements
-- longevity
-- data mining images requirements
-- data mining light curve requirements

Management
-- reliability / backups
-- scalability
-- cost-effective
-- no hierarchy

Experment with Swift on openstack-edinburgh
-- mirrormaker kafka cache
-- multiple ingesters
-- put images into swift
-- put light curves into swift

**Comment by gpfrancis** [comment]
Based on Stephen's responses to the email I've updated the requirements page at https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/865501225/Blob+Storage+Requirements and started a new page for shortlisted technologies at https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/885227561/Blob+Storage+Technology+Shortlist
