### ISSUE TITLE
Add Sherlock Catalogues - PS1 DR1 and Gaia DR2

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair#64]
The tcs_cat_ps1_dr1 and tcs_cat_gaia_dr2 catalogues need to be added to Sherlock, which runs on lasair-node0 or lasair-dev-node0.

Actions are:

1. Copy catalogues in place & change ownership & permissions
2. Restart the database processes on the node0 machines.
3. Add the new PS1 views.  See https://github.com/thespacedoctor/sherlock/issues/70.
4. Add the new sherlock algorithm to sherlock.yaml.  Do NOT do this before adding the new catalogues and views.

**Comment by genghisken** [comment]
The catalogue files are currently in this directory on lasair-node0.

```/data/sherlock_catalogues```

The tcs_cat_gaia_dr2 catalogue has been installed into lasair-node0, but NOT anywhere else yet.

Neither catalogue is currently installed on lasair-dev-node0.  (Data needs to be copied across from lasair-node0.

**Comment by genghisken** [comment]
Both the new catalogues (tcs_cat_ps1_dr1 and tcs_cat_gaia_dr2), and 5 new views have been installed on both lasair-node0 and lasair-dev-node0.  All is ready to go, but I can't find the relevant sherlock.yaml into which I need to install the new algorithm.  I suspect it is buried in the /home/roy account somewhere on lasair-head (and lasair-dev-head).

**Comment by RoyWilliams** [comment]
Sherlock is called on the production system when the following code is run
lasair-head: /home/roy/lasair/src/post_ingest/run_sherlock.py

The sherlock runs on lasair-node0 under the lasair account, the config is:
lasair-node0:/home/lasair/.config/sherlock/sherlock.yaml
------
Sherlock is called on the dev system when the following code is run
lasair-dev-head: /home/roy/lasair/src/post_ingest/run_sherlock.py

The sherlock runs on lasair-dev-node0 under the lasair account, the config is:
lasair-dev-node0:/home/lasair/.config/sherlock/sherlock.yaml

**Comment by genghisken** [comment]
Ah - stupid me - I was logging in as me, not the lasair user on lasair-dev, hence getting confused, since I also had a test sherlock instance installed into my account.

New algorithm installed on lasair-node0.  Also upgraded sherlock which was out of date.

New algorithm also installed on lasair-dev-node0.  New sherlock has never run correctly on this machine.  This is fixed now since upgrade of "fundamentals" package.

All sherlock versions are at v1.6.6
