### ISSUE TITLE
Make test topic (ZTF data)

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair#67]
Make a non-expiring test topic with ZTF data. Probably simply requires marking one of the existing nightly topics as non-expiring.

**Comment by gpfrancis** [comment]
Topic "ztf_test" created (hopefully with the right options to not expire) on the local ZTF mirror. Should contain a full copy of the data from the topic ztf_20200404_programid1.

**Comment by gpfrancis** [comment]
Assigned to Roy to review.

**Comment by RoyWilliams** [comment]
Works great. See below.

$ hostname
lasair-dev-head
$ source activate lasair
$ python bin/ingest_no_database.py --logging INFO --maxalert 100000 --nthread 8 --group LASAIR-DEV1 --host 192.41.108.22 --topic ztf_test

Configuration = {'bootstrap.servers': '192.41.108.22:9092', 'default.topic.config': {'auto.offset.reset': 'smallest'}, 'group.id': 'LASAIR-DEV1'}


3: finished with 10844 alerts
5: finished with 11271 alerts
2: finished with 11064 alerts
6: finished with 11508 alerts
4: finished with 12097 alerts
0: finished with 11698 alerts
1: finished with 11571 alerts
7: finished with 11868 alerts
Run time 286.738100
$
Total is 91921
matches the ZTF monitor for 2020404

**Comment by gpfrancis** [comment]
Thanks Roy.
