### ISSUE TITLE
Complete Lasair 2.0 documentation

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#69]
This has been accumulating on the wiki. Separate card for integration into website. The task here is to complete and review the docs

**Comment by genghisken** [comment]
Hi all - minor detail, but it occurs to me that we should not be referring anymore to the Large Synoptic Survey Telescope anywhere in our documentation.  Should be Vera C. Rubin Observatory.  I think it's only the home page that matters.  (I believe the LSST badge on the front of the site is OK.)

**Comment by andyxerxes** [comment]
At our review meeting, we decided that although there were some flaws, the current state of the user documentation is good enough for now, so we can declare this ticket "Done". Doing a rationalisation review of Lasair-ZTF documentation can be the first step in our planned Cycle-2 UI-review project.
