### ISSUE TITLE
Integrate Lasair/Sherlock docs

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#72]
Merge the Lasair user docs and the new Sherlock documentation into the Lasair-ZTF website. For now this only needs to be done in a simple and crude way. The whole user interface will be improved in a later project.

**Comment by genghisken** [comment]
The Sherlock documentation has now been integrated into the Lasair web interface. The only thing required is a git pull from the webserver machine (lasair-head), but I don't currently have access. If there are issues with the page, I won't know until the code is updated!

**Comment by andyxerxes** [comment]
Final remaining thing agreed was to rename the sidebar-item "Classification and Annotation" and then to add some words at the top of the page saying something along the lines of "Lasair does this stuff with a beast called Sherlock. Here is some info about how this works.." @genghisken said he would do this. Then we can declare this ticket done.

**Comment by genghisken** [comment]
Done. See the lasair-dev website.
