### ISSUE TITLE
Demo using Kafka to talk to Sherlock

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair#73]
Make a demo of using Kafka to handle the communication and load balancing between the ingest process and Sherlock.

**Comment by Zarquan** [comment]
I'm happy to have a go at building this, but at the moment I don't have time allocated to do it.

**Comment by gpfrancis** [comment]
Demo in https://github.com/lsst-uk/kafka-exp/tree/master/sherlock

**Comment by RoyWilliams** [comment]
It seems that Sherlock must have its requests batched, since it takes a long time to parse the config script, set up the database connection, etc. So the Kafka event will actually contain a batch of sky positions and return a batch of classifications. For sample request and response:

https://github.com/lsst-uk/lasair/tree/master/src/sherlock_web_wrapper/server/data

**Comment by gpfrancis** [comment]
I think in the long run we can fix that, but I don't see any reason why the wrapper can't handle the batching in a way that's transparent to the rest of the system. Roughly what sort of batch size were you anticipating?

**Comment by RoyWilliams** [comment]
I note that DaveY, myself, and you all have parts of this single application code in our own repo. When DaveY fixed sherlock, it was a delta from his original code, which of course I had already changed. So big merge job this afternoon. We need to work together on the same repo.

**Comment by gpfrancis** [comment]
Assuming that the "you" in the above refers to me - I don't think that's been the case so far. Yes, as soon as I start writing code which is actually going to be part of Lasair I'll try to put it in the Lasair repo, but I think random learning and experiments are better kept separate.

A better question is how do we manage the differences between Lasair-ZTF and Lasair-LSST?
