### ISSUE TITLE
Define and create Lasair 2.0 announcement

### ISSUE THREAD

**Issue by andyxerxes** [lsst-uk/lasair#74]
When everything is ready, we need to publicise the official release of Lasair 2.0 and Sherlock 2.0. By default this will be (a) On the LSST:UK public site, and (b) as some kind of news item on the Lasair website. We can also consider other mechanisms.

**Comment by andyxerxes** [comment]
I started writing my own wee plan for this, which I shall put together and share shortly. My thinking is:
* make LSST-UK news item
* a flash on "home" page
* make a "Lasair 2.0" release page
- link to this on "release notes" page
- link to this on home-flash 
- list new things in this release
  (Sherlock, documentation, recent additions)
  (implementation on IRIS)
  (stability and performance)
- link to roadmap page

I think this gives me enough to count this as "in progress"

**Comment by smarttgit** [comment]
Lasair 2.0 release news. I suggest : 

On front page put text : 

On 7th April 2020 we released the stable, functioning version 2.0 of the Lasair broker for processing ZTF alerts. The additions and improvements in this release are found on this page. 

Create a page, link from Lasair home with content:

Lasair 2.0 
On 7th April 2020 we released the stable, functioning version 2.0 of the Lasair broker for processing ZTF alerts. The additions and improvements in this release are 

- Documentation  **Insert links*
- A new, upgraded version of the context classifier Sherlock Version 2.0 **Insert link** 
- Lasair is now running on the the UK's IRIS high performance computing facility **insert generic link to IRIS** 
- We provide a forward look to our broad plans to develop Lasair for the LSST alert stream 
- Anything else (e.g. stability/performance) that Roy/Ken want to highlight

**Comment by smarttgit** [comment]
Suggest putting the above text under the heading Lasair 2.0 on the page 
https://lasair-dev.roe.ac.uk/about 
and 
https://lasair.roe.ac.uk/about

**Comment by RoyWilliams** [comment]
Lasair is not running on IRIS, it is on the LSST testbed at ROE

**Comment by smarttgit** [comment]
That'd fine, just write whatever it is running on

**Comment by RoyWilliams** [comment]
It says "Lasair provides Kafka output for query/filters: contact us for more information."

The reason I did not put the kafka endpoint address is that it is not a secure installation. Stellios has it on his to-do list to add access control so that only ourselves can put events into the kafka.

**Comment by andyxerxes** [comment]
Things remaining to do before this ticket is done:
(1) Draft text for LSST:UK web page news item
(2) Draft text for LSST:UK consortium mailshot
(3) Draft text for mailshot to Lasair registered users.

Then to send out those items!

**Comment by smarttgit** [comment]
Would suggest putting in the LSST:UK August Newsletter and the website and not do mail shots : 

(1) Draft text for LSST:UK web page news item
(2) Draft text for LSST:UK August Newsletter
