### ISSUE TITLE
Experiment with Cassandra on single node

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#92]
Ingest Lasair candidates database into a Cassandra instance. Run sample queries to understand limits.

**Comment by genghisken** [comment]
Cassandra installed on a single IRIS node.  Currently working on Ansible scripts to allow me to deploy the Cassandra node along with the software dependencies to allow insertion of multiple records in parallel.  (For load testing.)

**Comment by genghisken** [comment]
Web interface updated to allow polling of local single-node cassandra instance.  Still to do is get the ingest working.

**Comment by genghisken** [comment]
This is done now.  We have multi-node deployment
