### ISSUE TITLE
Install Cassandra on multinode openstack

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#93]
Get Belfast collabs running on IRIS@Edinburgh, install Cassandra. Run tests to detemine scaling with cluster size.

**Comment by genghisken** [comment]
Multinode instance deployment on hold until Ansible recipe is complete (see single node install).

**Comment by genghisken** [comment]
Can't progress this until the IRIS cluster is accessible again.

**Comment by genghisken** [comment]
5 small cassandra nodes instantiated.  Next is installation of the software and connecting the nodes together.  We need to test how replication works.

**Comment by genghisken** [comment]
Ansible scripts now created for deploying Cassandra and Anaconda with all the relevant python packages installed into a non-root user.

**Comment by genghisken** [comment]
Next task is to get the default configuration in place to get all the Cassandra nodes talking to each other.

**Comment by genghisken** [comment]
I have a default cassandra.yaml config file for the 5 node cluster.  I also have a default cassandra-rackdc.properties file.  These need to be altered for each node.

I need to figure out how to copy the files in place with Ansible and edit for each node.  For example I need to change the broadcast_rpc_address for each node to be the IP address of that node.

**Comment by genghisken** [comment]
All the nodes are now communicating.  I've figured out how to write the Ansible template correctly to place the relevant broadcast_rpc_address in the right place.
