### ISSUE TITLE
Decide how to implement New catalogs

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#98]
Define and implement a process so that new catalogues can be efficiently ingested and utilised in Sherlock

**Comment by thespacedoctor** [comment]
# Checklist for Adding a New Catalogue to the Sherlock Database.

There are 4 stages to adding a catalogue to the Sherlock database:

1. Understanding the catalogue, its content and the quality of the underlying data
2. Importing the catalogue into a new table in the Sherlock database
3. Mapping the catalogue columns so Sherlock can read it
4. Adding the catalogue into the search algorithm

## Understanding the catalogue, its content and the quality of the underlying data

This means reading and digesting the papers and/or documentation for the catalogue. It is vitally important to understand the quality of the catalogue’s source typing (AGN, Star, Galaxy ..) and also any distance measurements given in the catalogue. Note also where the weaknesses of the catalogue are (bright end, faint end?). All this information is used later to inform the search algorithm and the relative ranking of classifications.

## Importing the catalogue into a new table in the Sherlock database

Once the data has been downloaded to disk it needs to be read and converted into a MySQL table.

Here's the github repo for previous Sherlock import scripts [here](https://github.com/thespacedoctor/sherlock-import-scripts).

The frankenstein templating engine can be used to generate some quick-start boilerplate code:

```bash
mkdir bigsurvey_galaxies
frankenstein frankenstein-template/ bigsurvey_galaxies
please add your placeholder values ...
catalogue_url? > https://someurl.com
catalogue_name? > bigsurvey_galaxies
```

Or alternatively copy and amend a previous import script.

The code will format the name of the table correctly, so add a name like `bigsurvey_galaxies` and it will become `tcs_cat_bigsurvey_galaxies_dr2`. 

Here are some pointers for writing the script:

1. Add the version number of the catalogue in the code (e.g. `v1_0`)
2. In the `create_dictionary_...` method convert the input catalogue into a list of dictionaries and run the script to create a first pass at the MySQL table (you will have to open a tunnel to the Sherlock database and have that setup in the `sherlock.yaml` settings)
    - into the dictionary rename the RA and DEC columns to `raDeg` and `decDeg` so HMpTy can pick them up later to generate HTMids.
3. Open the table in MySQL Workbench and alter the table to set the correct columns types.
4. Add indexes for magnitude, coordinates, object type, distance columns and object name.
5. Copy the CREATE TABLE statement from MySQL Workbench and paste it into the `createStatement` in the ingest method.
6. Drop the table in MySQL Workbench
7. Remove the `convert_dictionary_to_mysql_table` code in the `create_dictionary_...` method
8. Uncomment the `catalogue.ingest()` call in the main function
9. Run the script again and check the results in MySQL Workbench
10. Tidy the script

## Mapping the catalogue columns so Sherlock can read it

1. `SELECT * FROM crossmatch_catalogues.tcs_helper_catalogue_tables_info;` and edit the entry for the new table (you may need to add new magnitude columns if the filter has not been seen before).
2. Retire any legacy tables via the `legacy` column.
3. Create/replace catalogue views for the search you want to do
4. Run `sherlock clean`
5. `SELECT * FROM crossmatch_catalogues.tcs_helper_catalogue_views_info;` and add the table ID associated with the new views

## Adding the catalogue into the search algorithm

There is a stand-alone Sherlock script that can be used alongside a set of test transients. This is useful to develop the search algorithm against as it does not need to write to a database, returning crossmatches and classifications to the std-out.

1. Clone the Sherlock [stand-alone script gist](https://gist.github.com/thespacedoctor/5ed7e1f4018dc2c501b0d9b9d8f6cbff).
2. `cp ~/.config/sherlock/sherlock.yaml new_cat_test.yaml`
3. Edit the `new_cat_test.yaml` to host ONLY the new search modules, for example for LAS-r:

    ```python
    LASr galaxy:
        database table: tcs_view_galaxy_lasr_v1
        mag column: W1
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 240.0
            synonym: NT
            association: SN
    LASr agn:
        database table: tcs_view_agn_lasr_v1
        mag column: W1
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 240.0
            synonym: AGN
            association: SN
    ```
    
4. Run the stand-alone script, inspect the results and tune the algorithm until you’re happy:

    ```bash
    python sherlock_query_example.py -s new_cat_test.yaml -i atlas4_good_list.csv
    ```
    
5. Finally deploy the new search modules to the sherlock algorithm yaml files across all systems using the service.

**Comment by thespacedoctor** [comment]
I've now added the checklist to confluence.
