### ISSUE TITLE
Define questions for user requirements review meeting

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair#99]
Define questions for the review panel about the science objectives for Lasair.
See https://lsst-uk.atlassian.net/wiki/spaces/LUSCSWG/pages/1150287885/Lasair+User+Requirements+review+2020

**Comment by andyxerxes** [comment]
Obviously this is done, and we don't have an official reviewer assigned. (How do we do that anyway?) But I thought maybe we could get in the habit of reviewing before closing. So maybe I just ask Roy and Stephen to add comments here saying "yes this done". Or maybe we approve it at the next telecon?
